service: serverless-s3
provider:
  name: aws
  deploymentMethod: direct
  region: eu-west-2
  stage: dev


resources:
  # S3
  - ${file(resources/s3-bucket.yml)}

functions:
  - ${file(./python-functions.yml)}

plugins:
  - serverless-python-requirements